package Conductores;

/**
* Conductores/ConductorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conductor.idl
* miércoles 14 de noviembre de 2018 11:26:48 AM COT
*/

public final class ConductorHolder implements org.omg.CORBA.portable.Streamable
{
  public Conductores.Conductor value = null;

  public ConductorHolder ()
  {
  }

  public ConductorHolder (Conductores.Conductor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Conductores.ConductorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Conductores.ConductorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Conductores.ConductorHelper.type ();
  }

}
