package Conductores;


/**
* Conductores/Conductor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conductor.idl
* miércoles 14 de noviembre de 2018 11:26:48 AM COT
*/

public interface Conductor extends ConductorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conductor
