package Conductores;


/**
* Conductores/ConductorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conductor.idl
* miércoles 14 de noviembre de 2018 11:26:48 AM COT
*/

public interface ConductorOperations 
{
  boolean insertarConductor (int id, String nombre, int telefono, String placa);
  boolean actualizarConductor (int id, String nombre, int telefono, String placa);
  boolean eliminarConductor (int id);
  String consultarConductor (int id);
  void shutdown ();
} // interface ConductorOperations
