package Proveedores;


/**
* Proveedores/ProveedorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedor.idl
* miércoles 7 de noviembre de 2018 04:31:17 PM COT
*/

public interface ProveedorOperations 
{
  boolean insertarProveedor (int codigoProveedor, String nombre, String telefono, String direccion);
  boolean actualizarProveedor (int codigoProveedor, String nombre, int telefono, String direccion);
  boolean eliminarProveedor (int codProveedor);
  String consultarProveedor (int codProveedor);
  void shutdown ();
} // interface ProveedorOperations
