package Proveedores;


/**
* Proveedores/Proveedor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from proveedor.idl
* miércoles 7 de noviembre de 2018 04:31:17 PM COT
*/

public interface Proveedor extends ProveedorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedor
