package Producto;


/**
* Producto/Productos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from producto.idl
* viernes 9 de noviembre de 2018 03:25:08 PM COT
*/

public interface Productos extends ProductosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Productos
