/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabajo_Final;
//

import javax.swing.table.DefaultTableModel;
import javax.xml.bind.annotation.XmlElement;
import Sentencias.*;
import com.mysql.jdbc.ResultSetImpl;
import com.sun.net.httpserver.Filter;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class cliente extends javax.swing.JFrame {

    private DefaultTableModel modeloTable;

    public cliente() {
        modeloTable = new DefaultTableModel(null, getColumn());

        initComponents();

        this.setTitle("cliente");
        this.setLocation(400, 220);
    }

    private String[] getColumn() {
        String columnas[] = new String[]{"nit", "nombre", "apellido", "telefono", "direccion"};
        return columnas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblcliente = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txt_nombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txt_nit = new javax.swing.JLabel();
        txtnit = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblModel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblcliente.setBackground(new java.awt.Color(255, 255, 102));

        jButton1.setText("vista principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_nombre.setText("nombre");
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txt_apellido.setText("apellido");

        txt_telefono.setText("telefono");

        txt_nit.setText("nit");

        txtnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnitActionPerformed(evt);
            }
        });
        txtnit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnitKeyTyped(evt);
            }
        });

        txt_direccion.setText("direccion");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblModel.setModel(modeloTable);
        jScrollPane1.setViewportView(tblModel);

        javax.swing.GroupLayout tblclienteLayout = new javax.swing.GroupLayout(tblcliente);
        tblcliente.setLayout(tblclienteLayout);
        tblclienteLayout.setHorizontalGroup(
            tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tblclienteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(tblclienteLayout.createSequentialGroup()
                            .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_apellido)
                                .addComponent(txt_nit))
                            .addGap(2, 2, 2)))
                    .addComponent(txt_direccion)
                    .addComponent(txt_telefono))
                .addGap(18, 18, 18)
                .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tblclienteLayout.createSequentialGroup()
                        .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(tblclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdicionar)
                .addGap(47, 47, 47)
                .addComponent(btnEliminar)
                .addGap(47, 47, 47)
                .addComponent(btnBuscar)
                .addGap(46, 46, 46)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(80, 80, 80)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        tblclienteLayout.setVerticalGroup(
            tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tblclienteLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tblclienteLayout.createSequentialGroup()
                        .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nit)
                            .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombre))
                        .addGap(35, 35, 35)
                        .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_apellido)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_telefono)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccion)))
                    .addGroup(tblclienteLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129)
                .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tblclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnBuscar)
                        .addComponent(btnAdicionar)
                        .addComponent(btnLimpiar))
                    .addComponent(jButton1)
                    .addComponent(btnSalir))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tblcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaPrincipal obj = new VistaPrincipal();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnitActionPerformed

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        //Validar los campos vac{ios
        if (txtnit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese nit");
            txtnit.requestFocus();
            return;
        }

        if (txtnombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese nombre");
            txtnombre.requestFocus();
            return;
        }
        if (txtapellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese apellido");
            txtapellido.requestFocus();
            return;
        }

        if (txttelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Telefono");
            txttelefono.requestFocus();
            return;
        }

        if (txtdireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese Direccion");
            txtdireccion.requestFocus();
            return;


    }//GEN-LAST:event_btnAdicionarActionPerformed
        //Instancio la clase 
        TablaCliente objTablaCliente = new TablaCliente();

        //Declaro variables
        int nit;
        String nombre;
        String apellido;
        int telefono;
        String direccion;

        //Asigno los valores del formualrio 
        nit = Integer.parseInt(txtnit.getText());
        nombre = txtnombre.getText();
        apellido = txtapellido.getText();
        telefono = Integer.parseInt(txttelefono.getText());
        direccion = txtdireccion.getText();

        boolean resultado = objTablaCliente.insertarCliente(nit, nombre, apellido, telefono, direccion);
        if (resultado == true) {
            JOptionPane.showMessageDialog(null, "Registro exitoso");
        } else {
            JOptionPane.showMessageDialog(null, "Registro no exitoso");

        }

        //Limpio los campos
        txtnit.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");
        txtdireccion.setText("");

    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        TablaCliente objTablaCliente = new TablaCliente();

        //Asigno el modelo para el Jtable
        DefaultTableModel modeloTable = (DefaultTableModel) tblModel.getModel();

        //Asigno el indice del elemento seleccionado
        int indice = tblModel.getSelectedRow();

        //Asigno el campo de codigo al elemento a eliminar
        int codigo = (int) modeloTable.getValueAt(indice, 0);

        //Elimino el registro de la tabla
        modeloTable.removeRow(indice);

        //Elimino el registro de la BD
        boolean resultado = objTablaCliente.eliminarCliente(codigo);

        if (resultado == true) {
            JOptionPane.showMessageDialog(null, "Registro elimano correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Registro elimano correctamente");

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modeloTable.setNumRows(0);

        TablaCliente objTablaCliente = new TablaCliente();
        ResultSet resultado = objTablaCliente.cargarCliente();
        try {
            Object data[] = new Object[5];
            while (resultado.next()) {
                for (int i = 0; i < 5; i++) {
                    data[i] = resultado.getObject(i + 1);
                }
                modeloTable.addRow(data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        //Limpio los campos
        txtnit.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");
        txtdireccion.setText("");

        //Limpio las filas y columnas
        modeloTable.setNumRows(0);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtnitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnitKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "solo numeros");
        }
    }//GEN-LAST:event_txtnitKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblModel;
    private javax.swing.JPanel tblcliente;
    private javax.swing.JLabel txt_apellido;
    private javax.swing.JLabel txt_direccion;
    private javax.swing.JLabel txt_nit;
    private javax.swing.JLabel txt_nombre;
    private javax.swing.JLabel txt_telefono;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnit;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
