package Ventas;


/**
* Ventas/Venta.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* miércoles 14 de noviembre de 2018 11:52:01 AM COT
*/

public interface Venta extends VentaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Venta
