package Ventas;


/**
* Ventas/VentaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from venta.idl
* miércoles 14 de noviembre de 2018 11:52:01 AM COT
*/

public interface VentaOperations 
{
  boolean insertarVenta (int id_venta, double subtotal, double iva, double total_pagar);
  boolean actualizarVenta (int id_venta, double subtotal, double iva, double total_pagar);
  boolean eliminarVenta (int id_venta);
  String consultarVenta (int id_venta);
  void shutdown ();
} // interface VentaOperations
