package Sucursales;

/**
* Sucursales/SucursalHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* miércoles 14 de noviembre de 2018 09:33:53 AM COT
*/

public final class SucursalHolder implements org.omg.CORBA.portable.Streamable
{
  public Sucursales.Sucursal value = null;

  public SucursalHolder ()
  {
  }

  public SucursalHolder (Sucursales.Sucursal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Sucursales.SucursalHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Sucursales.SucursalHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Sucursales.SucursalHelper.type ();
  }

}
