package Sucursales;


/**
* Sucursales/Sucursal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* miércoles 14 de noviembre de 2018 09:33:53 AM COT
*/

public interface Sucursal extends SucursalOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sucursal
