package Sucursales;


/**
* Sucursales/SucursalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sucursal.idl
* miércoles 14 de noviembre de 2018 09:33:53 AM COT
*/

public interface SucursalOperations 
{
  boolean insertarSucursal (int codigo, String ciudad, int telefono, String direccion);
  boolean actualizarSucursal (int codigo, String ciudad, int telefono, String direccion);
  boolean eliminarSucursal (int Codigo);
  String consultarSucursal (int Codigo);
  void shutdown ();
} // interface SucursalOperations
